<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SmoViewer\SmoViewer.Core\SmoViewer.Core.csproj" />
    <ProjectReference Include="..\..\SmoExporter\SmoExporter.Core\SmoExporter.Core.csproj" />
    <ProjectReference Include="..\..\SMOTextureTool\SMOTextureTool.Core\SMOTextureTool.Core.csproj" />
  </ItemGroup>
</Project>
