#!/usr/bin/env python3
"""Whole original automatic weighted draw with an initial generating cache miss.

Unchanged64KiB engine arena. Pure SDK/device fixture data use their existing
declared4KiB interface pages. Prepared template uses actual constructors and
one populated pass vector; XML/file acquisition is not part of this test.
"""
from pathlib import Path
import json,sys
from pc_instruction_emulator import run_bounded
from pc_serializer_fixtures import PCWriteBytesFixture
from pc_stl_fixtures import install_char_traits
from pc_crt_format_fixtures import install_sprintf
from pc_shader_compiler_fixtures import ShaderCompilerOutput
from probe_pc_function_eval import cleanup,bits

def main(mode,return_capture=False):
    if mode not in ('generated','failed-device'):raise ValueError('bounded automatic generated draw')
    f=PCWriteBytesFixture();p=f.p;install_char_traits(p);install_sprintf(p)
    sdk=ShaderCompilerOutput(p,constants=(('MatDiffuse',0,1),),compact_storage=True)
    renderer=p.allocate(0xf2f8);r=renderer;p.put_uint(0x75db68,r)
    p.put_uint(r,0x6f2918);p.put_uint(r+0x18,0x6f28a0)
    base=0x34100000;p.mu.mem_map(base,0x1000,p.uc.UC_PROT_READ|p.uc.UC_PROT_EXEC)
    device=base+0x400;table=base+0x500;handle=base+0x700;hvt=base+0x710
    p.put_uint(r+0xc9e8,device);p.put_uint(device,table);p.put_uint(handle,hvt);p.put_uint(hvt+8,base+16)
    events=[];tokens={0:0};maximum=0;checks=0
    def check(ok,label):
        nonlocal checks
        checks+=1
        if not ok:raise AssertionError(label)
    def call(entry,this=0,args=()):
        nonlocal maximum
        result=f.call(entry,this=this,args=args);maximum=max(maximum,sum(p.visits.values()));return result
    def state():return [tokens[p.uint(r+0xe454)],tokens[p.uint(r+0xe44c)],p.uint(r+0xe444),[p.uint(r+0xcbc4+4*i) for i in range(4)]]
    def release(machine):
        check(machine.uint(machine.reg('ESP')+4)==handle,'generated device handle release');events.append(['release',1]);machine.fixture_return(4,eax=0)
    p.seams[base+16]=release
    def create(machine):
        d,code,output=[machine.uint(machine.reg('ESP')+4+4*i) for i in range(3)]
        check(d==device and bytes(machine.mu.mem_read(code,5))==sdk.bytecode,'just-generated bytecode reaches original device call')
        tokens[output-0x50]=1;machine.put_uint(output,handle);events.append(['create',sdk.bytecode.hex(),state()]);machine.fixture_return(12,eax=0x80004005 if mode=='failed-device' else 0)
    p.put_uint(table+0x16c,base+32);p.seams[base+32]=create
    def observe(machine,name,argc):
        args=[machine.uint(machine.reg('ESP')+4+4*i) for i in range(argc)]
        if args[0]!=device:raise AssertionError('exact device self')
        if name=='vertex-constants':
            check(args[1]==0 and args[3]==1,'one fully initialized constant row')
            event=[name,0,[machine.uint(args[2]+4*i) for i in range(4)],1]
        elif name=='vertex-shader':event=[name,int(args[1]==handle)]
        else:event=[name,*args[1:]]
        events.append([*event,state()]);machine.fixture_return(argc*4,eax=0x80004005 if mode=='failed-device' else 0)
    for offset,(slot,name,argc) in enumerate(((0x170,'vertex-shader',2),(0x178,'vertex-constants',4),(0x148,'indexed',7)),3):
        entry=base+16*offset;p.put_uint(table+slot,entry);p.seams[entry]=lambda machine,n=name,a=argc:observe(machine,n,a)
    empty=p.allocate(28);call(0x450d90,this=empty)
    template=p.allocate(0x68);f.allocations[template]=0x68;p.mu.mem_write(template,b'\xcc'*0x68);call(0x4d0960,this=template,args=(1,empty,2))
    # Prepared one-element vector, built with the actual pass constructor.
    record=p.allocate(0x1dc);f.allocations[record]=0x1dc;p.mu.mem_write(record,b'\xcc'*0x1dc);call(0x4d5120,this=record)
    for offset,value in ((0x48,record),(0x4c,record+0x1dc),(0x50,record+0x1dc)):p.put_uint(template+offset,value)
    call(0x4cffc0,this=record)
    for offset,value in ((0x38,b'Main'),(0x54,b'vs_2_0')):
        source=p.allocate(len(value)+1);p.mu.mem_write(source,value+b'\0');call(0x4cfe20,this=record+0xd4+offset,args=(source,))
    manager=call(0x4c9680);p.put_uint(manager+0x40,template);p.put_uint(0x763024,manager)
    material=call(0x4a9460);p.put_uint(material+0xb8,0);p.put_uint(r+0xe47c,material)
    captures=[]
    for iteration in range(2):
        p.put_floats(material+0x78,(.25,.5,.75,float(iteration)));events.clear()
        result=call(0x4bc290,this=r,args=(2,11,13,17,19,0x803,0))&255
        check(result==1 and p.visits.get(0x4ae930) and p.visits.get(0x4be210),'actual auto selection/constants/draw completes')
        check(bool(p.visits.get(0x4c89eb))==(iteration==0),'first draw generates, second draws from cache')
        check(len(sdk.calls)==1 and p.uint(manager+0x4c)==1,'one generated shader retained')
        captures.append([iteration,result,state(),list(events)])
    events.clear();call(0x59a660,this=empty);cleanup(f,(material,manager))
    check(set(sdk.released)=={sdk.buffer,sdk.table},'all compiler SDK results released')
    capture=[mode,sdk.calls,captures,events]
    if not return_capture:print('RENDERER_GENERATED_CAPTURE',json.dumps(capture),flush=True)
    print(f'PASS {checks}/{checks}: whole original automatic generated draw {mode}; maxInstructions={maximum}; heap={p.allocated}',flush=True)
    return capture if return_capture else 0

if __name__=='__main__':
    if sys.argv[1:2]==['--guest']:raise SystemExit(main(sys.argv[2]))
    raise SystemExit(run_bounded(Path(__file__),sys.argv[1:]))
