<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmoViewer.Core\SmoViewer.Core.csproj" />
    <ProjectReference Include="..\SmoViewer.Scene\SmoViewer.Scene.csproj" />
    <ProjectReference Include="..\SmoViewer.Corpus\SmoViewer.Corpus.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SmoViewer.Editing/SmoViewer.Editing.csproj" />
  </ItemGroup>
</Project>
